### PR TITLE
Add string numbers - python

### LINKED ISSUE #8: Challenge: add string numbers
Writing a python function to add two numbers that are in string format and return the result as string.

### PR DESCRIPTION
**Pull request by Fahim-Ahmad**
- [x] PR's title includes the challenge's name and language
- [ ] PR has short and clear description of the challenge
- [x] PR has appropriate labels and milestones for easy identification
- [x] PR it is assigned to the owner
- [x] reviewers are assigned
- [x] the PR contributes only one focused change
- [x] the branch is up to date with `main`/`master`
- [x] the code works when pulled and run locally
- [x] all conflicts are resolved (if any)
- [x] It is linked to an issue in the appropriate column of the project board
- [x] feedback is addressed (if any, and if it is appropriate feedback.)

## README Documentation

- [x] The solution is documented in `/src/README.md`
- [x] The markdown source is formatted
- [x] Spelling and grammar is correct in all text
- [x] The markdown looks correct when you preview the file
- [x] All links and images work
- [x] The README documents the solution's behavior, strategy(ies) and implementation(s)
- [x] There are use cases in code blocks to illustrate the function's behavior

## Python Files

- [x] There is a module header
- [x] There is a module docstring
- [x] File names are in snake_case
- [x] Test files are named `test_<module_name>.py`

## Function Docstring

- [x] Behavior description
- [x] Parameter description
- [x] Return value description
- [x] Include any assumptions
- [ ] Include 3 or more (passing!) doctests
- [x] Include 1-2 use cases (if necessary)

## Function Implementation

- [x] The solution is not is not copied from [djeada](https://github.com/djeada/Algorithms-And-Data-Structures)
- [x] The code is auto-formatted
- [x] The code has no (reasonable) linting mistakes
- [ ] Variables are named with snake_case
- [x] The function has a clear and helpful name
- [x] The file's name matches the function name
- [x] The code follows the strategy as simply as possible
- [x] Variable names are clear and helpful
- [ ] Comments explain the strategy (if necessary)
- [ ] There are type annotations
- [ ] (challenge) The code includes defensive assertions

## Unit Test Suite

- [x] The test class has a helpful name in PascalCase
- [ ] The test class has a docstring
- Each unit test has
  - [x] A helpful name
  - [ ] A clear docstring
  - [x] Only one assertion
- [x] All tests pass
- [ ] There are tests for defensive assertions
- [ ] There are tests for boundary cases
- [ ] Test suite includes black-box and glass-box tests

### CODE REVIEW

**Comment by abed42** [comment]
Hi @Fahim-Ahmad , sulotions is great and pr almost ready to merge, however there's these minor things that would be nice if you resolve :
 It is linked to an issue in the appropriate column of the project board
 There is a module header
 There is a module docstring

**Comment by Fahim-Ahmad** [comment]
Hi @abed42 , thanks for point it out.
I added the module header and it is linked to its respected issue. So merging it will automatically close the issue too.

**Comment by abed42** [comment]
> Hi @abed42 , thanks for point it out. I added the module header and it is linked to its respected issue. So merging it will automatically close the issue too.


i can't find the module header up here on github. any chance you haven't pushed it up yet?

**Comment by abed42** [comment]
> > Hi @abed42 , thanks for point it out. I added the module header and it is linked to its respected issue. So merging it will automatically close the issue too.

> i can't find the module header up here on github. any chance you haven't pushed it up yet?

never mind my previous comment i see it now

**Pull request merged**
